language: node_js
node_js: lts/*
cache:
    directories:
    - node_modules
script:
- npm install # install node module
- npm run build # build project
- npm install -g firebase-tools
after_success:
- firebase use --token ${FIREBASE_TOKEN} # set firebase token
- firebase use --add ${PROJECT_ID} # set current project
- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" # deploy project